name: Send Discord Notification

on:
  workflow_dispatch: # Allows API triggers from GitHub Pages

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content": "@LCJUNIOR1220 Someone Went To https://scratchapps.github.io"}' \
          "$DISCORD_WEBHOOK"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORDWEBHOOK }}
