name: Send Discord Notification

on:
  workflow_dispatch: # Allows API triggers from GitHub Pages

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate and Trigger Workflow
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/ScratchApps/scratchapps.github.io/actions/workflows/webhook.yml/dispatches \
          -d '{"ref": "main"}'

      - name: Send Discord Notification
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content": "@LCJUNIOR1220 Someone Went To https://scratchapps.github.io"}' \
          "$DISCORD_WEBHOOK"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
