name: Send Discord Webhook on Visit

on:
  repository_dispatch:
    types: [page-visit]

jobs:
  send_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.PAT_TOKEN2 }}" \
          -H "Accept": "application/vnd.github+json" \
          -H "Content-Type": "application/json" \
          --data '{"content": "@LCJUNIOR1220 Someone Went To https://scratchapps.github.io"}' \
          "$DISCORD_WEBHOOK"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
